[package]
name = "snow-rs"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.29.0"
ctrlc = "3.4.7"
rand = "0.9.1"
